final Map<String, dynamic> tempMatchesListData = {
  "typeMatches": [
    {
      "matchType": "International",
      "seriesMatches": [
        {
          "seriesAdWrapper": {
            "seriesId": 8504,
            "seriesName": "West Indies tour of Pakistan, 2025",
            "matches": [
              {
                "matchInfo": {
                  "matchId": 101053,
                  "seriesId": 8504,
                  "seriesName": "West Indies tour of Pakistan, 2025",
                  "matchDesc": "1st Test",
                  "matchFormat": "TEST",
                  "startDate": "1737088200000",
                  "endDate": "1737459000000",
                  "state": "Stumps",
                  "status": "Day 1: Stumps",
                  "team1": {"teamId": 3, "teamName": "Pakistan", "teamSName": "PAK", "imageId": 591986},
                  "team2": {"teamId": 10, "teamName": "West Indies", "teamSName": "WI", "imageId": 172124},
                  "venueInfo": {"id": 22, "ground": "Multan Cricket Stadium", "city": "Multan", "timezone": "+05:00", "latitude": "30.170782", "longitude": "71.524727"},
                  "currBatTeamId": 3,
                  "seriesStartDt": "1736467200000",
                  "seriesEndDt": "1738195200000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Stumps"
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 143, "wickets": 4, "overs": 41.3}
                  },
                  "team2Score": {}
                }
              }
            ]
          }
        },
        {
          "adDetail": {"name": "native_matches", "layout": "native_large", "position": 1}
        }
      ]
    },
    {
      "matchType": "League",
      "seriesMatches": [
        {
          "seriesAdWrapper": {
            "seriesId": 8535,
            "seriesName": "Big Bash League 2024-25",
            "matches": [
              {
                "matchInfo": {
                  "matchId": 101797,
                  "seriesId": 8535,
                  "seriesName": "Big Bash League 2024-25",
                  "matchDesc": "37th Match",
                  "matchFormat": "T20",
                  "startDate": "1737101700000",
                  "endDate": "1737114300000",
                  "state": "Complete",
                  "status": "No result due to rain",
                  "team1": {"teamId": 192, "teamName": "Sydney Thunder", "teamSName": "SYT", "imageId": 172252},
                  "team2": {"teamId": 198, "teamName": "Sydney Sixers", "teamSName": "SYS", "imageId": 172258},
                  "venueInfo": {"id": 34, "ground": "Sydney Cricket Ground", "city": "Sydney", "timezone": "+11:00", "latitude": "-33.868820", "longitude": "151.209296"},
                  "seriesStartDt": "1734220800000",
                  "seriesEndDt": "1738108800000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Complete",
                  "isFantasyEnabled": true
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 36, "wickets": 1, "overs": 5.1}
                  }
                }
              }
            ]
          }
        },
        {
          "seriesAdWrapper": {
            "seriesId": 9201,
            "seriesName": "Bangladesh Premier League, 2024-25",
            "matches": [
              {
                "matchInfo": {
                  "matchId": 109877,
                  "seriesId": 9201,
                  "seriesName": "Bangladesh Premier League, 2024-25",
                  "matchDesc": "24th Match",
                  "matchFormat": "T20",
                  "startDate": "1737118800000",
                  "endDate": "1737131400000",
                  "state": "In Progress",
                  "status": "Chittagong Kings opt to bowl",
                  "team1": {"teamId": 256, "teamName": "Rangpur Riders", "teamSName": "RGR", "imageId": 172309},
                  "team2": {"teamId": 202, "teamName": "Chittagong Kings", "teamSName": "CK", "imageId": 172262},
                  "venueInfo": {"id": 93, "ground": "Zahur Ahmed Chowdhury Stadium", "city": "Chattogram", "timezone": "+06:00", "latitude": "22.355898", "longitude": "91.767766"},
                  "currBatTeamId": 256,
                  "seriesStartDt": "1735516800000",
                  "seriesEndDt": "1739059200000",
                  "isTimeAnnounced": true,
                  "stateTitle": "In Progress"
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 81, "wickets": 4, "overs": 12.4}
                  }
                }
              },
              {
                "matchInfo": {
                  "matchId": 109869,
                  "seriesId": 9201,
                  "seriesName": "Bangladesh Premier League, 2024-25",
                  "matchDesc": "23rd Match",
                  "matchFormat": "T20",
                  "startDate": "1737100800000",
                  "endDate": "1737113400000",
                  "state": "Complete",
                  "status": "Durbar Rajshahi won by 65 runs",
                  "team1": {"teamId": 2233, "teamName": "Durbar Rajshahi", "teamSName": "DBR", "imageId": 592543},
                  "team2": {"teamId": 1412, "teamName": "Sylhet Strikers", "teamSName": "SYST", "imageId": 253023},
                  "venueInfo": {"id": 93, "ground": "Zahur Ahmed Chowdhury Stadium", "city": "Chattogram", "timezone": "+06:00", "latitude": "22.355898", "longitude": "91.767766"},
                  "currBatTeamId": 2233,
                  "seriesStartDt": "1735516800000",
                  "seriesEndDt": "1739059200000",
                  "isTimeAnnounced": true,
                  "stateTitle": "DBR Won"
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 184, "wickets": 7, "overs": 19.6}
                  },
                  "team2Score": {
                    "inngs1": {"inningsId": 2, "runs": 119, "wickets": 10, "overs": 17.3}
                  }
                }
              }
            ]
          }
        },
        {
          "seriesAdWrapper": {
            "seriesId": 9261,
            "seriesName": "International League T20, 2025",
            "matches": [
              {
                "matchInfo": {
                  "matchId": 111145,
                  "seriesId": 9261,
                  "seriesName": "International League T20, 2025",
                  "matchDesc": "8th Match",
                  "matchFormat": "T20",
                  "startDate": "1737124200000",
                  "endDate": "1737136800000",
                  "state": "Toss",
                  "status": "Sharjah Warriorz opt to bowl",
                  "team1": {"teamId": 1312, "teamName": "Sharjah Warriorz", "teamSName": "SW", "imageId": 249197},
                  "team2": {"teamId": 1298, "teamName": "Dubai Capitals", "teamSName": "DCP", "imageId": 249194},
                  "venueInfo": {"id": 140, "ground": "Sharjah Cricket Stadium", "city": "Sharjah", "timezone": "+04:00", "latitude": "25.33095", "longitude": "55.420902"},
                  "seriesStartDt": "1736553600000",
                  "seriesEndDt": "1739232000000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Toss",
                  "isFantasyEnabled": true
                }
              }
            ]
          }
        }
      ]
    },
    {
      "matchType": "Domestic",
      "seriesMatches": [
        {
          "seriesAdWrapper": {
            "seriesId": 9333,
            "seriesName": "England Under 19 tour of South Africa, 2025",
            "matches": [
              {
                "matchInfo": {
                  "matchId": 112518,
                  "seriesId": 9333,
                  "seriesName": "England Under 19 tour of South Africa, 2025",
                  "matchDesc": "1st Youth ODI",
                  "matchFormat": "ODI",
                  "startDate": "1737100800000",
                  "endDate": "1737129600000",
                  "state": "Toss",
                  "status": "South Africa U19 opt to bat",
                  "team1": {"teamId": 57, "teamName": "South Africa U19", "teamSName": "RSAU19", "imageId": 172159},
                  "team2": {"teamId": 173, "teamName": "England U19", "teamSName": "ENGU19", "imageId": 172241},
                  "venueInfo": {"id": 1402, "ground": "Western Province Cricket Club", "city": "Cape Town", "timezone": "+02:00", "latitude": "-33.919060", "longitude": "18.421961"},
                  "seriesStartDt": "1737072000000",
                  "seriesEndDt": "1738972800000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Toss"
                }
              }
            ]
          }
        },
        {
          "seriesAdWrapper": {
            "seriesId": 8714,
            "seriesName": "CSA Four-Day Series Division Two 2024-25",
            "matches": [
              {
                "matchInfo": {
                  "matchId": 104388,
                  "seriesId": 8714,
                  "seriesName": "CSA Four-Day Series Division Two 2024-25",
                  "matchDesc": "14th Match",
                  "matchFormat": "TEST",
                  "startDate": "1737014400000",
                  "endDate": "1737298800000",
                  "state": "Stumps",
                  "status": "Day 1: Stumps",
                  "team1": {"teamId": 1766, "teamName": "KwaZulu-Natal Inland", "teamSName": "KZNIN", "imageId": 349611},
                  "team2": {"teamId": 912, "teamName": "Limpopo", "teamSName": "LIMPO", "imageId": 248430},
                  "venueInfo": {"id": 772, "ground": "Polokwane Cricket Club", "city": "Polokwane", "timezone": "+02:00", "latitude": "-23.912260", "longitude": "29.453550"},
                  "currBatTeamId": 1766,
                  "seriesStartDt": "1730332800000",
                  "seriesEndDt": "1744070400000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Stumps"
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 64, "wickets": 3, "overs": 28.6}
                  },
                  "team2Score": {}
                }
              },
              {
                "matchInfo": {
                  "matchId": 104396,
                  "seriesId": 8714,
                  "seriesName": "CSA Four-Day Series Division Two 2024-25",
                  "matchDesc": "15th Match",
                  "matchFormat": "TEST",
                  "startDate": "1737014400000",
                  "endDate": "1737298800000",
                  "state": "Stumps",
                  "status": "Day 1: Stumps - South Western Districts trail by 196 runs",
                  "team1": {"teamId": 903, "teamName": "Mpumalanga Rhinos", "teamSName": "MPR", "imageId": 248434},
                  "team2": {"teamId": 1768, "teamName": "South Western Districts", "teamSName": "SWD", "imageId": 349609},
                  "venueInfo": {"id": 1193, "ground": "Uplands College, White River", "city": "Mpumalanga", "timezone": "+02:00", "latitude": "-25.328440", "longitude": "31.017780"},
                  "currBatTeamId": 1768,
                  "seriesStartDt": "1730332800000",
                  "seriesEndDt": "1744070400000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Stumps"
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 226, "wickets": 10, "overs": 52.3}
                  },
                  "team2Score": {
                    "inngs1": {"inningsId": 2, "runs": 30, "overs": 9.6}
                  }
                }
              },
              {
                "matchInfo": {
                  "matchId": 104386,
                  "seriesId": 8714,
                  "seriesName": "CSA Four-Day Series Division Two 2024-25",
                  "matchDesc": "13th Match",
                  "matchFormat": "TEST",
                  "startDate": "1737014400000",
                  "endDate": "1737298800000",
                  "state": "Stumps",
                  "status": "Day 1: Stumps ",
                  "team1": {"teamId": 923, "teamName": "Northern Cape", "teamSName": "NCAPE", "imageId": 248438},
                  "team2": {"teamId": 933, "teamName": "Eastern Storm", "teamSName": "ESTORM", "imageId": 248407},
                  "venueInfo": {"id": 148, "ground": "Diamond Oval", "city": "Kimberley", "timezone": "+02:00", "latitude": "-28.742487", "longitude": "24.742101"},
                  "currBatTeamId": 923,
                  "seriesStartDt": "1730332800000",
                  "seriesEndDt": "1744070400000",
                  "isTimeAnnounced": true,
                  "stateTitle": "Stumps"
                },
                "matchScore": {
                  "team1Score": {
                    "inngs1": {"inningsId": 1, "runs": 292, "wickets": 8, "overs": 90.6}
                  },
                  "team2Score": {}
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "filters": {
    "matchType": ["International", "League", "Domestic", "Women"]
  },
  "appIndex": {"seoTitle": "Live Cricket Score - Scorecard and Match Results", "webURL": "www.cricbuzz.com/live-cricket-scores/"},
  "responseLastUpdated": "1737123416"
}; // as matchesList?;


final Map<String, dynamic> tempMatchDetailData = {
  "scoreCard":[
    {
      "matchId":111185,
      "inningsId":1,
      "timeScore":1737476398000,
      "batTeamDetails":{
        "batTeamId":1307,
        "batTeamName":"MI Emirates",
        "batTeamShortName":"MIE",
        "batsmenData":{
          "bat_1":{
            "batId":8116,
            "batName":"Kusal Perera",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":23,
            "balls":20,
            "dots":0,
            "fours":5,
            "sixes":0,
            "mins":0,
            "strikeRate":115.0,
            "outDesc":"c Ibrar Ahmad b Holder",
            "bowlerId":8313,
            "fielderId1":1447401,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":5,
            "sixers":0,
            "wicketCode":"CAUGHT",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_2":{
            "batId":18987,
            "batName":"Muhammad Waseem",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":38,
            "balls":35,
            "dots":0,
            "fours":1,
            "sixes":3,
            "mins":0,
            "strikeRate":108.57,
            "outDesc":"b Ibrar Ahmad",
            "bowlerId":1447401,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":1,
            "sixers":3,
            "wicketCode":"BOWLED",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_3":{
            "batId":12254,
            "batName":"Tom Banton",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":9,
            "balls":9,
            "dots":0,
            "fours":1,
            "sixes":0,
            "mins":0,
            "strikeRate":100.0,
            "outDesc":"run out (Willey)",
            "bowlerId":0,
            "fielderId1":6592,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":1,
            "sixers":0,
            "wicketCode":"RUNOUT",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_4":{
            "batId":9406,
            "batName":"Pooran",
            "batShortName":"",
            "isCaptain":true,
            "isKeeper":true,
            "runs":49,
            "balls":26,
            "dots":0,
            "fours":5,
            "sixes":2,
            "mins":0,
            "strikeRate":188.46,
            "outDesc":"c Alishan Sharafu b Holder",
            "bowlerId":8313,
            "fielderId1":14227,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":5,
            "sixers":2,
            "wicketCode":"CAUGHT",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_5":{
            "batId":657,
            "batName":"Pollard",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":5,
            "balls":10,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":50.0,
            "outDesc":"b Ali Khan",
            "bowlerId":11450,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"BOWLED",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_6":{
            "batId":15243,
            "batName":"Mousley",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":6,
            "balls":7,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":85.71,
            "outDesc":"c Laurie Evans b Ali Khan",
            "bowlerId":11450,
            "fielderId1":6531,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"CAUGHT",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_7":{
            "batId":13646,
            "batName":"Romario Shepherd",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":38,
            "balls":13,
            "dots":0,
            "fours":4,
            "sixes":3,
            "mins":0,
            "strikeRate":292.31,
            "outDesc":"not out",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":4,
            "sixers":3,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_8":{
            "batId":8435,
            "batName":"Akeal Hosein",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":2,
            "balls":2,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":100.0,
            "outDesc":"not out",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_9":{
            "batId":12247,
            "batName":"Zahoor Khan",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_10":{
            "batId":14282,
            "batName":"Fazalhaq Farooqi",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_11":{
            "batId":11220,
            "batName":"Alzarri Joseph",
            "batShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          }
        }
      },
      "bowlTeamDetails":{
        "bowlTeamId":1300,
        "bowlTeamName":"Abu Dhabi Knight Riders",
        "bowlTeamShortName":"ADKR",
        "bowlersData":{
          "bowl_4":{
            "bowlerId":1447401,
            "bowlName":"Ibrar Ahmad",
            "bowlShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "overs":2.0,
            "maidens":0,
            "runs":21,
            "wickets":1,
            "economy":10.5,
            "no_balls":2,
            "wides":4,
            "dots":0,
            "balls":20,
            "runsPerBall":1.05,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bowl_3":{
            "bowlerId":8313,
            "bowlName":"Holder",
            "bowlShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "overs":4.0,
            "maidens":0,
            "runs":38,
            "wickets":2,
            "economy":9.5,
            "no_balls":0,
            "wides":2,
            "dots":0,
            "balls":40,
            "runsPerBall":0.95,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bowl_6":{
            "bowlerId":11450,
            "bowlName":"Ali Khan",
            "bowlShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "overs":4.0,
            "maidens":0,
            "runs":58,
            "wickets":2,
            "economy":14.5,
            "no_balls":0,
            "wides":2,
            "dots":0,
            "balls":40,
            "runsPerBall":1.45,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bowl_5":{
            "bowlerId":2276,
            "bowlName":"Narine",
            "bowlShortName":"",
            "isCaptain":true,
            "isKeeper":false,
            "overs":4.0,
            "maidens":0,
            "runs":24,
            "wickets":0,
            "economy":6.0,
            "no_balls":0,
            "wides":0,
            "dots":0,
            "balls":40,
            "runsPerBall":0.6,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bowl_2":{
            "bowlerId":8440,
            "bowlName":"K Mayers",
            "bowlShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "overs":2.0,
            "maidens":0,
            "runs":11,
            "wickets":0,
            "economy":5.5,
            "no_balls":0,
            "wides":0,
            "dots":0,
            "balls":20,
            "runsPerBall":0.55,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bowl_1":{
            "bowlerId":6592,
            "bowlName":"Willey",
            "bowlShortName":"",
            "isCaptain":false,
            "isKeeper":false,
            "overs":4.0,
            "maidens":0,
            "runs":30,
            "wickets":0,
            "economy":7.5,
            "no_balls":0,
            "wides":2,
            "dots":0,
            "balls":40,
            "runsPerBall":0.75,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          }
        }
      },
      "scoreDetails":{
        "ballNbr":120,
        "isDeclared":false,
        "isFollowOn":false,
        "overs":20.0,
        "revisedOvers":0.0,
        "runRate":9.3,
        "runs":186,
        "wickets":6,
        "runsPerBall":0.93
      },
      "extrasData":{
        "noBalls":2,
        "total":16,
        "byes":0,
        "penalty":0,
        "wides":10,
        "legByes":4
      },
      "ppData":{

      },
      "wicketsData":{
        "wkt_1":{
          "batId":8116,
          "batName":"Kusal Perera",
          "wktNbr":1,
          "wktOver":5.3,
          "wktRuns":42,
          "ballNbr":53
        },
        "wkt_2":{
          "batId":12254,
          "batName":"Tom Banton",
          "wktNbr":2,
          "wktOver":10.0,
          "wktRuns":80,
          "ballNbr":100
        },
        "wkt_3":{
          "batId":18987,
          "batName":"Muhammad Waseem",
          "wktNbr":3,
          "wktOver":10.3,
          "wktRuns":83,
          "ballNbr":103
        },
        "wkt_4":{
          "batId":657,
          "batName":"Pollard",
          "wktNbr":4,
          "wktOver":13.3,
          "wktRuns":102,
          "ballNbr":133
        },
        "wkt_5":{
          "batId":15243,
          "batName":"Mousley",
          "wktNbr":5,
          "wktOver":15.5,
          "wktRuns":119,
          "ballNbr":155
        },
        "wkt_6":{
          "batId":9406,
          "batName":"Pooran",
          "wktNbr":6,
          "wktOver":18.3,
          "wktRuns":150,
          "ballNbr":183
        }
      },
      "partnershipsData":{
        "pat_1":{
          "bat1Id":8116,
          "bat1Name":"Kusal Perera",
          "bat1Runs":23,
          "bat1fours":5,
          "bat1sixes":0,
          "bat2Id":18987,
          "bat2Name":"Muhammad Waseem",
          "bat2Runs":14,
          "bat2fours":1,
          "bat2sixes":1,
          "totalRuns":42,
          "totalBalls":33,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        },
        "pat_2":{
          "bat1Id":12254,
          "bat1Name":"Tom Banton",
          "bat1Runs":9,
          "bat1fours":1,
          "bat1sixes":0,
          "bat2Id":18987,
          "bat2Name":"Muhammad Waseem",
          "bat2Runs":23,
          "bat2fours":0,
          "bat2sixes":2,
          "totalRuns":38,
          "totalBalls":29,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        },
        "pat_3":{
          "bat1Id":9406,
          "bat1Name":"Pooran",
          "bat1Runs":1,
          "bat1fours":0,
          "bat1sixes":0,
          "bat2Id":18987,
          "bat2Name":"Muhammad Waseem",
          "bat2Runs":1,
          "bat2fours":0,
          "bat2sixes":0,
          "totalRuns":3,
          "totalBalls":3,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        },
        "pat_4":{
          "bat1Id":9406,
          "bat1Name":"Pooran",
          "bat1Runs":14,
          "bat1fours":2,
          "bat1sixes":0,
          "bat2Id":657,
          "bat2Name":"Pollard",
          "bat2Runs":5,
          "bat2fours":0,
          "bat2sixes":0,
          "totalRuns":19,
          "totalBalls":18,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        },
        "pat_5":{
          "bat1Id":9406,
          "bat1Name":"Pooran",
          "bat1Runs":10,
          "bat1fours":1,
          "bat1sixes":0,
          "bat2Id":15243,
          "bat2Name":"Mousley",
          "bat2Runs":6,
          "bat2fours":0,
          "bat2sixes":0,
          "totalRuns":17,
          "totalBalls":14,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        },
        "pat_6":{
          "bat1Id":9406,
          "bat1Name":"Pooran",
          "bat1Runs":24,
          "bat1fours":2,
          "bat1sixes":2,
          "bat2Id":13646,
          "bat2Name":"Shepherd",
          "bat2Runs":4,
          "bat2fours":0,
          "bat2sixes":0,
          "totalRuns":31,
          "totalBalls":16,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        },
        "pat_7":{
          "bat1Id":8435,
          "bat1Name":"Akeal Hosein",
          "bat1Runs":2,
          "bat1fours":0,
          "bat1sixes":0,
          "bat2Id":13646,
          "bat2Name":"Shepherd",
          "bat2Runs":34,
          "bat2fours":4,
          "bat2sixes":3,
          "totalRuns":36,
          "totalBalls":9,
          "bat1balls":0,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":0,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        }
      }
    },
    {
      "matchId":111185,
      "inningsId":2,
      "timeScore":1737477444000,
      "batTeamDetails":{
        "batTeamId":1300,
        "batTeamName":"Abu Dhabi Knight Riders",
        "batTeamShortName":"ADKR",
        "batsmenData":{
          "bat_1":{
            "batId":8440,
            "batName":"Kyle Mayers",
            "batShortName":"K Mayers",
            "isCaptain":false,
            "isKeeper":false,
            "runs":6,
            "balls":5,
            "dots":4,
            "fours":0,
            "sixes":1,
            "mins":0,
            "strikeRate":120.0,
            "outDesc":"batting",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":1,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_2":{
            "batId":11959,
            "batName":"Andries Gous",
            "batShortName":"Andries Gous",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"batting",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_3":{
            "batId":9815,
            "batName":"Joe Clarke",
            "batShortName":"Joe Clarke",
            "isCaptain":false,
            "isKeeper":true,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_4":{
            "batId":13800,
            "batName":"Michael-Kyle Pepper",
            "batShortName":"Michael Pepper",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_5":{
            "batId":14227,
            "batName":"Alishan Sharafu",
            "batShortName":"Alishan Sharafu",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_6":{
            "batId":2276,
            "batName":"Sunil Narine",
            "batShortName":"Narine",
            "isCaptain":true,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_7":{
            "batId":6531,
            "batName":"Laurie Evans",
            "batShortName":"Laurie Evans",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_8":{
            "batId":8313,
            "batName":"Jason Holder",
            "batShortName":"Holder",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_9":{
            "batId":6592,
            "batName":"David Willey",
            "batShortName":"Willey",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_10":{
            "batId":1447401,
            "batName":"Ibrar Ahmad",
            "batShortName":"Ibrar Ahmad",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          },
          "bat_11":{
            "batId":11450,
            "batName":"Ali Khan",
            "batShortName":"Ali Khan",
            "isCaptain":false,
            "isKeeper":false,
            "runs":0,
            "balls":0,
            "dots":0,
            "fours":0,
            "sixes":0,
            "mins":0,
            "strikeRate":0.0,
            "outDesc":"",
            "bowlerId":0,
            "fielderId1":0,
            "fielderId2":0,
            "fielderId3":0,
            "ones":0,
            "twos":0,
            "threes":0,
            "fives":0,
            "boundaries":0,
            "sixers":0,
            "wicketCode":"",
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          }
        }
      },
      "bowlTeamDetails":{
        "bowlTeamId":1307,
        "bowlTeamName":"MI Emirates",
        "bowlTeamShortName":"MIE",
        "bowlersData":{
          "bowl_1":{
            "bowlerId":8435,
            "bowlName":"Akeal Hosein",
            "bowlShortName":"Akeal Hosein",
            "isCaptain":false,
            "isKeeper":false,
            "overs":0.5,
            "maidens":0,
            "runs":6,
            "wickets":0,
            "economy":7.2,
            "no_balls":0,
            "wides":0,
            "dots":0,
            "balls":5,
            "runsPerBall":1.2,
            "isOverseas":false,
            "inMatchChange":"",
            "playingXIChange":""
          }
        }
      },
      "scoreDetails":{
        "ballNbr":5,
        "isDeclared":false,
        "isFollowOn":false,
        "overs":0.5,
        "revisedOvers":0.0,
        "runRate":7.2,
        "runs":6,
        "wickets":0,
        "runsPerBall":1.2
      },
      "extrasData":{
        "noBalls":0,
        "total":0,
        "byes":0,
        "penalty":0,
        "wides":0,
        "legByes":0
      },
      "ppData":{

      },
      "wicketsData":{

      },
      "partnershipsData":{
        "pat_1":{
          "bat1Id":8440,
          "bat1Name":"Mayers",
          "bat1Runs":6,
          "bat1fours":0,
          "bat1sixes":1,
          "bat2Id":11959,
          "bat2Name":"Gous",
          "bat2Runs":0,
          "bat2fours":0,
          "bat2sixes":0,
          "totalRuns":6,
          "totalBalls":5,
          "bat1balls":5,
          "bat2balls":0,
          "bat1Ones":0,
          "bat1Twos":0,
          "bat1Threes":0,
          "bat1Fives":0,
          "bat1Boundaries":0,
          "bat1Sixers":1,
          "bat2Ones":0,
          "bat2Twos":0,
          "bat2Threes":0,
          "bat2Fives":0,
          "bat2Boundaries":0,
          "bat2Sixers":0
        }
      }
    }
  ],
  "matchHeader":{
    "matchId":111185,
    "matchDescription":"14th Match",
    "matchFormat":"HUN",
    "matchType":"league",
    "complete":false,
    "domestic":false,
    "matchStartTimestamp":1737469800000,
    "matchCompleteTimestamp":1737480600000,
    "dayNight":true,
    "year":2025,
    "state":"In Progress",
    "status":"Abu Dhabi Knight Riders need 181 runs",
    "tossResults":{
      "tossWinnerId":1300,
      "tossWinnerName":"Abu Dhabi Knight Riders",
      "decision":"Bowling"
    },
    "result":{
      "winningTeam":"",
      "winByRuns":false,
      "winByInnings":false
    },
    "revisedTarget":{
      "reason":""
    },
    "playersOfTheMatch":[

    ],
    "playersOfTheSeries":[

    ],
    "matchTeamInfo":[
      {
        "battingTeamId":1307,
        "battingTeamShortName":"MIE",
        "bowlingTeamId":1300,
        "bowlingTeamShortName":"ADKR"
      },
      {
        "battingTeamId":1300,
        "battingTeamShortName":"ADKR",
        "bowlingTeamId":1307,
        "bowlingTeamShortName":"MIE"
      }
    ],
    "isMatchNotCovered":false,
    "team1":{
      "id":1300,
      "name":"Abu Dhabi Knight Riders",
      "playerDetails":[

      ],
      "shortName":"ADKR"
    },
    "team2":{
      "id":1307,
      "name":"MI Emirates",
      "playerDetails":[

      ],
      "shortName":"MIE"
    },
    "seriesDesc":"International League T20, 2025",
    "seriesId":9261,
    "seriesName":"International League T20, 2025",
    "alertType":"auto",
    "livestreamEnabled":false
  },
  "isMatchComplete":false,
  "status":"Abu Dhabi Knight Riders need 181 runs",
  "videos":[

  ],
  "responseLastUpdated":1737477462
};